import {nurtureScheduleSummary} from './nurture-schedule';
import {NurtureTemplates} from './nurture-templates';
import {Play,RotateCcw,Save} from 'lucide-react';
import type {ReactNode} from 'react';
type Config=Record<string,string|number|boolean|string[]>;
const surfaces=[['feed','首页动态'],['reels','Reels'],['stories','快拍'],['post','指定帖子'],['profile','指定主页'],['search','搜索']] as const;
export function NurtureTemplate({config,set,selected,busy,schedule,onStart,onSave,onRestore,onReset}:{config:Config;set:(key:string,value:Config[string])=>void;selected:number;busy:boolean;schedule:ReactNode;onStart:()=>void;onSave:()=>void;onRestore:()=>void;onReset:()=>void}){
  const active=(config.surfaces as string[])||[];
  const number=(key:string,label:string,min:number,max:number|undefined)=><label className="formal-field"><span>{label}</span><input className="formal-input" type="number" min={min} max={max} step={1} value={String(config[key]??'')} onChange={e=>set(key,e.target.value===''?'':Number(e.target.value))}/></label>;
  const text=(key:string,label:string,placeholder:string)=><label className="formal-field"><span>{label}</span><textarea className="formal-input" rows={4} placeholder={placeholder} value={(config[key] as string[]||[]).join('\n')} onChange={e=>set(key,e.target.value.split('\n'))}/></label>;
  const bounds:Record<string,[number,number]>={rounds:[1,20],minutes:[1,120],dwell_min:[3,300],dwell_max:[3,300],concurrency:[0,Number.MAX_SAFE_INTEGER],interval_seconds:[0,86400]};
  for(const action of ['like','save','follow','comment']){bounds[action+'_probability']=[0,100];bounds[action+'_limit']=[0,action==='comment'?50:100];}
  const invalid=Object.entries(bounds).some(([k,[lo,hi]])=>config[k]===''||!Number.isInteger(Number(config[k]))||Number(config[k])<lo||Number(config[k])>hi);
  const commentIssue=Number(config.comment_probability)>0&&Number(config.comment_limit)>0&&!(config.comments as string[]||[]).some(v=>v.trim());
  const issue=commentIssue?'启用评论前请填写评论内容':!active.length?'至少选择一种浏览内容':invalid?'请将计划参数填写在输入框标明的范围内':Number(config.dwell_min)>Number(config.dwell_max)?'最长停留不能小于最短停留':active.includes('search')&&!String(config.keywords||'').trim()?'请填写搜索关键词':(active.includes('post')||active.includes('profile'))&&!(config.targets as string[]||[]).some(v=>v.trim())?'请填写指定帖子链接或主页账号':'';
  return <section className="formal-panel nurture-template"><div className="formal-panel-header"><h2>养号模板</h2><div className="studio-controls"><button className="formal-button compact" disabled={busy} onClick={onRestore}><RotateCcw size={15}/>载入已保存模板</button><button className="formal-button compact" disabled={busy} onClick={onReset}>恢复默认</button></div></div><fieldset disabled={busy}><NurtureTemplates busy={busy} onApply={values=>Object.entries(values).forEach(([key,value])=>set(key,value))}/>
    <div className="nurture-template-grid"><section><h3>01 · 浏览计划</h3><div className="studio-form-grid"><label className="formal-field"><span>阶段标签</span><select className="formal-input" value={String(config.stage)} onChange={e=>set('stage',e.target.value)}>{['适应期','稳定期','维护期'].map(v=><option key={v}>{v}</option>)}</select></label>{number('rounds','每窗口轮次 · 1–20',1,20)}{number('minutes','每轮分钟 · 1–120',1,120)}{number('concurrency','同时执行窗口数 · 0 为全部所选',0,undefined)}{number('dwell_min','最短停留秒数 · 3–300',3,300)}{number('dwell_max','最长停留秒数 · 3–300',3,300)}{number('interval_seconds','相邻计划错开秒数 · 0–86400',0,86400)}{schedule}</div><p className="studio-muted">计划总数：{selected * Number(config.rounds||0)}；每窗口累计浏览约 {Number(config.rounds||0)*Number(config.minutes||0)} 分钟。</p></section>
    <section><h3>02 · 浏览内容</h3><div className="nurture-surfaces">{surfaces.map(([key,label])=><label className={active.includes(key)?'is-selected':''} key={key}><input type="checkbox" checked={active.includes(key)} onChange={()=>set('surfaces',active.includes(key)?active.filter(v=>v!==key):[...active,key])}/>{label}</label>)}</div>{active.includes('search')&&<label className="formal-field"><span>搜索关键词</span><input className="formal-input" maxLength={300} value={String(config.keywords||'')} onChange={e=>set('keywords',e.target.value)}/></label>}{(active.includes('profile')||active.includes('post'))&&text('targets','目标账号 / 帖子链接 · 每行一个','主页：username 或 Instagram 主页链接\n帖子：https://www.instagram.com/p/…/')}</section>
    <section className="nurture-interactions"><h3>03 · 互动设置</h3><div className="formal-table-scroll"><table className="studio-table"><thead><tr><th>动作</th><th>每步概率 · %</th><th>每日上限</th></tr></thead><tbody>{[['like','点赞',100],['save','收藏',100],['follow','关注',100],['comment','评论',50]].map(([key,label,max])=><tr key={key}><td>{label}</td><td>{number(key+'_probability',label+'概率',0,100)}</td><td>{number(key+'_limit',label+'上限',0,Number(max))}</td></tr>)}</tbody></table></div>{Number(config.comment_probability)>0&&Number(config.comment_limit)>0&&text('comments','评论内容 · 每行一条','填写实际需要发送的评论')}</section></div>
    <div className="nurture-template-footer"><span role="status">{issue||nurtureScheduleSummary(selected,Number(config.concurrency),Number(config.interval_seconds),String(config.scheduled_at||''))}</span><button className="formal-button" disabled={Boolean(issue)} onClick={onSave}><Save size={16}/>保存养号模板</button><button className="formal-button primary" disabled={!selected||Boolean(issue)} onClick={onStart}><Play size={16}/>生成计划并执行</button></div>
  </fieldset></section>;
}
